---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8

inputs:
- name: source-code

run:
  path: sh
  args:
  - -exc
  - |
    cd source-code
    ls -lah
    ./gradlew test
    echo "all tests pass"