---
resources:
- name: source-code
  type: git
  check_every: 10s
  source:
    uri: ((gitRepository))
    branch: master
jobs:
- name: test
  plan:
  - get: source-code
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8
      inputs:
      - name: source-code
      run:
        path: sh
        args:
        - -exc
        - |
          cd source-code
          ls -lah
          ./gradlew test
          echo "all tests pass"