---
resources:
- name: source-code
  type: git
  check_every: 10s
  source:
    uri: ((gitRepository))
    branch: lab-finish
jobs:
- name: test
  plan:
  - get: source-code
    trigger: true
  - task: test
    file: source-code/ci/tasks/test.yml